Allow setting unit on `put`, `putSummary` and `sample`
mixmaxhq/cloudwatch-metrics pull request #33
Opened 2020-09-10 11:08 UTC by Nevon

#### Changes Made

`put`, `putSummary` and `sample` now all accept a `units` argument, allowing you to have multiple metrics for the same namespace with different units. For example:

```js
const namespace = new Metric('Server', 'Count');

namespace.put(1, 'RequestCount')
namespace.put(500, 'RequestBodySize', 'Bytes')
```

The implementation gets a little funky because I didn't want to break backwards compatibility, while still retaining a logical argument order. So the way I have implemented it, both the old function signatures and the new ones should work:

```js
const dimensions = [{ Name: 'environment', Value: 'production' }]

// `units` will be inherited from the namespace and the dimensions will be respected
namespace.put(1, 'RequestCount', dimensions)

// Overrides `units` from the namespace
namespace.put(500, 'RequestBodySize', 'Bytes', dimensions)
```

Fixes #13

#### Potential Risks

* The tests are updated to include usages of both the new and old signatures, but if there is a mistake that the tests don't catch, the likely result would be that the `dimensions` will be used as the unit, which I would assume would cause CloudWatch to reject the request.
* Having functions that accept a variable number of arguments is pretty gnarly to maintain, so in the long run I would advocate for a breaking change that removes the unit from the namespace and requires it on the metric itself, but that's just my recommendation.

#### Test Plan

* The automated tests are testing both the new and old function signatures.

#### Checklist
- [x] I've increased test coverage
- [x] Since this is a public repository, I've checked I'm not publishing private data in the code, commit comments, or this PR.

2021-01-12 21:07 UTC, ttacon requested changes
Thanks for the awesome PR and our apologies on the very late reply. Just a few comments and then this looks good to merge.

2021-01-12 21:07 UTC, ttacon commented on index.js
> +    const units = Array.isArray(args[2]) ? this.units : args[2];
Let's do the same as above and extract the `Array.isArray(args[2])` check so that we can reuse it here and the line below.

2021-01-12 21:07 UTC, ttacon commented on index.js
> +    return this._put(args[0], args[1], units, additionalDimensions);
Any reason not to destructure the first arguments of `args` as we do below (i.e. `const [value, metricName] = args;`)?

2021-01-13 07:58 UTC, Nevon commented
PR comments addressed in 28c91f8.

2021-01-13 15:32 UTC, ttacon approved these changes
Thanks for the PR!

2021-01-14 16:25 UTC, merged

2021-01-14 16:29 UTC, ttacon commented
Release in v1.3.0